site_name: Forest MQ

nav:
  - Home: index.md
  - Protocol: protocol.md

theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: limer
    toggle:
      icon: material/weather-night
      name: Switch to light mode